---
- name: "Teste de comandos shell"
  hosts: "{{groups['srv01']}}"
  gather_facts: no


  tasks:

      - name: install pexpect
        pip:
          name: pexpect
        become: yes
      
      - name: Teste de acesso
        ansible.builtin.shell: |
          set timeout -1
          spawn ssh root@{{ item }}
          sleep 5
          send "VMware1!\r"

          sleep 5
          
          send -- "curl {{ hostvars['localhost'].['port01'] }}\r"

          sleep 10

          send -- "exit\r"

          expect eof

        args:
          executable: /usr/bin/expect
        #delegate_to: localhost
        loop: "{{groups['host02']}}"
        register: connection_out


      - name: "Resultado telnet"
        ansible.builtin.debug:
            msg: 
              - "{{ connection_out }}"
            #  - "{{ connection_out2 }}"
        #run_once: true  