---
- name: "Teste de comandos shell"
  hosts: "{{groups['srv01']}}"
  gather_facts: no
  vars:


  tasks:

      - name: install pexpect
        pip:
          name: pexpect
        become: yes
      
      - name: Teste de acesso
        ansible.builtin.shell: |
          set timeout -1
          spawn ssh root@{{ item }}
          sleep 5
          send -- "VMware1!\r"

          sleep 5
          
          send -- "curl localhost:{{hostvars[item].ansible_port}}\r"

          sleep 2

          send -- "curl localhost:{{hostvars[item].ansible_port2}}\r"
          
          sleep 2
          
          send -- "exit\r"

          expect eof

        args:
          executable: /usr/bin/expect
        #delegate_to: localhost
        loop: "{{groups['host02']}}"
        register: connection_out

      
      
      - name: debug
        debug:
          msg: "{{ connection_out.stdout_lines | regex_search('.*teste.*', ignorecase=True) }}"
      
      #- name: "Resultado telnet"
      #  ansible.builtin.debug:
      #      msg: "{{ connection_out }}"
      #  with_items: "{{ connection_out.results }}"  
      #  when: "{{ connection_out.stdout == 'root'}}"
            #  - "{{ connection_out2 }}"
        #run_once: true  