---
- name: "Teste de comandos shell"
  hosts: "{{groups['srv01']}}"
  gather_facts: no
  
  tasks:

      - name: install pexpect
        pip:
          name: pexpect
        become: yes
      
      - name: Teste de acesso
        ansible.builtin.shell: |
          set timeout -1
          spawn ssh root@{{ item.0 }}
          sleep 5
          send -- "VMware1!\r"

          sleep 5
          
          send -- "curl localhost:{{ item.1 }}\r"

          sleep 2
         
          send -- "exit\r"

          expect eof

        args:
          executable: /usr/bin/expect
        #delegate_to: localhost
        loop: "{{'groups[host02]' | 'hostvars[host02].ansible_port' | list }}" 
        register: connection_out

      - name: "Consolidando Resultado"
        ansible.builtin.template:
          src: switch.j2
          dest: "/tmp/teste-yaml/conncect-{{inventory_hostname}}.csv"
        register: rc02

      - name: "Resultado telnet"
        ansible.builtin.debug:
            msg: "{{ connection_out.results }}"
        run_once: true

      #  with_items: "{{ connection_out.results }}"  
      #  when: "{{ connection_out.stdout == 'root'}}"
            #  - "{{ connection_out2 }}"
        #run_once: true  