---
- name: "Teste de comandos shell"
  hosts: "{{groups['srv01']}}"
  gather_facts: no


  tasks:

      - name: install pexpect
        pip:
          name: pexpect
        become: yes
      
      - name: Teste de acesso
        ansible.builtin.shell: |
          set timeout 60
          spawn ssh root@{{ item }}
      
          expect "password:" {send "VMware1!\r"}

          expect "[root@{{ item }} ~]#" {send "df -lh\r"}

          exit 0

        args:
          executable: /usr/bin/expect
        #delegate_to: localhost
        loop: "{{groups['host02']}}"
        register: connection_out


      - name: "Resultado telnet"
        ansible.builtin.debug:
            msg: "{{ connection_out }}"
        #run_once: true  