---
- name: "Teste de comandos shell"
  hosts: "{{groups['srv01']}}"
  gather_facts: no


  tasks:

      - name: install pexpect
        pip:
          name: pexpect
        become: yes
      
      - name: Teste de acesso
        ansible.builtin.shell: |
          set timeout 5
          spawn ssh root@{{ item }}

          expect "*?erprint:*"
          send " yes\n"

          expect "*?assword:*"
          send " VMware1!\n"

          expect "\n root"
          send "df -lh\n"

          exit 0
        args:
          executable: /usr/bin/expect
        #delegate_to: localhost
        loop: "{{groups['host02']}}"
        register: connection_out


      - name: "Resultado telnet"
        ansible.builtin.debug:
            msg: "{{ connection_out.results[0] }}"
        run_once: true  